# Generated by Django 3.1.5 on 2021-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Half time', 'Half time'), ('Full time', 'Full time')], max_length=100)),
                ('job_description', models.TextField(max_length=2000)),
                ('job_requirement', models.TextField(max_length=2000)),
                ('job_salary_range', models.FloatField()),
                ('years_of_experience', models.IntegerField()),
                ('job_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
