# Generated by Django 3.1.5 on 2021-02-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='job',
            new_name='applying_job',
        ),
    ]
