# Generated by Django 3.1.5 on 2021-02-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210202_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='tag',
        ),
        migrations.AddField(
            model_name='candidate',
            name='tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tag'),
        ),
    ]
