# Generated by Django 3.1.5 on 2021-02-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag_tag_meaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='tag',
        ),
        migrations.AddField(
            model_name='candidate',
            name='tag',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
