# Generated by Django 3.1.5 on 2021-02-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210202_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('order_category', models.CharField(choices=[('snacks', 'snacks'), ('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=100)),
                ('customer_category', models.CharField(choices=[('regular', 'regular'), ('new', 'new')], max_length=100)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('food', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
