# Generated by Django 3.2.4 on 2021-07-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='updated_date',
            new_name='update_date',
        ),
    ]
