# Generated by Django 3.1.2 on 2021-08-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReduxShop', '0002_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ReduxShop.product'),
        ),
    ]
