# Generated by Django 3.1.2 on 2021-08-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReduxShop', '0003_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
