# Generated by Django 3.1.4 on 2021-06-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210613_1336'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
