export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE";

export const RESET_BOOKING = "RESET_BOOKING";

export const LOAD_BOOKED_ROOM = "LOAD_BOOKED_ROOM";
export const BOOKED_ROOM_LOADING_FAILED = "BOOKED_ROOM_LOADING_FAILED";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
