# Generated by Django 3.1.4 on 2021-02-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210207_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='newOne',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
