export const ADD_COMMENT = "ADD_COMMENT";
export const LOAD_PHOTO = "LOAD_PHOTO";
export const PHOTO_LOADING = "PHOTO_LOADING";

export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const COMMENT_LOADING = "COMMENT_LOADING";

export const PHOTOS_FAILED = "PHOTOS_FAILED";
